### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by nesi73** [nv-nguyen/cnos#29]
The first run was executed without any issues (`bash run_inference_custom.sh`). However, when repeating the same operation, it fails to work. I have checked the GPU memory using nvidia-smi before running the process to ensure it's not full, and it shows only 300MiB out of 16376MiB in use.

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 15.99 GiB total capacity; 5.76 GiB already allocated; 8.75 GiB free; 5.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by nesi73** [comment]
using fast_sam.yaml instead of sam.yaml works for me

**Comment by Moerliy** [comment]
I'm having the same issue. Switching to `fast_sam` fixed it temporarily, but even there, I get a similar error after a while.
For sam:
```sh
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 23.63 GiB total capacity; 3.75 GiB already allocated; 1.05 GiB free; 3.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Inference failed.
```

For fast_sam:
```sh
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.63 GiB (GPU 0; 23.63 GiB total capacity; 3.18 GiB already allocated; 1.64 GiB free; 3.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Inference failed.
```
